apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primary-pvc
  namespace: primary
  annotations:
    trident.netapp.io/shareToNamespace: secondary
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: storage-class-nas